-- AlterTable
ALTER TABLE "Space" ADD COLUMN     "affiliateLink" TEXT,
ADD COLUMN     "allowSearchEngineIndexing" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoPopulateWallOfLove" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "consentDisplay" TEXT NOT NULL DEFAULT 'required',
ADD COLUMN     "consentStatement" TEXT NOT NULL DEFAULT 'I give permission to use this testimonial.',
ADD COLUMN     "defaultAvatarUrl" TEXT,
ADD COLUMN     "disableVideoForIphone" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxTextCharacters" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "maxVideoDuration" INTEGER NOT NULL DEFAULT 120,
ADD COLUMN     "openGraphDescription" TEXT,
ADD COLUMN     "openGraphImageUrl" TEXT,
ADD COLUMN     "openGraphTitle" TEXT,
ADD COLUMN     "questionLabel" TEXT NOT NULL DEFAULT 'Questions',
ADD COLUMN     "textButtonText" TEXT NOT NULL DEFAULT 'Send in text',
ADD COLUMN     "textSubmissionTitle" TEXT NOT NULL DEFAULT 'Title',
ADD COLUMN     "thirdPartyReviewLink" TEXT,
ADD COLUMN     "thirdPartyReviewPlatform" TEXT,
ADD COLUMN     "videoButtonText" TEXT NOT NULL DEFAULT 'Record a video';
